### PR TITLE
[Type Checking] Enables typechecking; Closes #31;

### LINKED ISSUE #31: It is not behaving as expected
I define an interface, then pass it to my Component as Props and/or State the interface doesn't really apply.
Because if I try to create a state variable diferrent from the interface it doesn't throw any error neither points the error out.

But if I implement a function (like someFunction()) with typed params and try to call it, VS Code will tell me it is wrong, but still tsc will not throw an error.

Check it out here:
```
import React from 'react';

interface ops {
  a: number;
}

class Index extends React.Component<ops, ops> {
  constructor(props: ops){
    
    super(props);

    //Should tell me there is no "b" in the state's type
    this.state = {
      b: 'olar'
    }
  }

  someFunction(param1: string, param2: number){
    return param1+param2.toString();
  }

  render(){
    return(
      <div>
        { this.someFunction(5, {attr: 'it is behaving as expected'}) }
      </div>
    );  
  }

}

export default Index;
```
My tsconfig.json file:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "jsx": "preserve",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "lib": [
      "dom",
      "es2015",
      "es2016"
    ]
  }
}
```

What am I doing wrong?

### PR DESCRIPTION
**Pull request by zscaiosi**
Resolves the problem reporter on #31

### CODE REVIEW

File: packages/next-typescript/index.js [hunk 1]
```diff
@@ -1,4 +1,7 @@
-module.exports = (nextConfig = {}) => {
+module.exports = (nextConfig = {}, customs) => {
+
+  const { isTranspileOnly } = customs;
```
Comment (timneutkens) [inline packages/next-typescript/index.js]: Lets read from `nextConfig` instead of adding another parameter.

Also call it `typescriptLoaderOptions`

File: packages/next-typescript/index.js [hunk 2]
```diff
@@ -19,7 +22,7 @@ module.exports = (nextConfig = {}) => {
           {
             loader: 'ts-loader',
             options: {
-              transpileOnly: true
+              transpileOnly: isTranspileOnly == null ? true : isTranspileOnly
```
Comment (timneutkens) [inline packages/next-typescript/index.js]: Lets do it like this:

```
options: Object.keys({}, {
  transpileOnly: true
}, typescriptLoaderOptions)
```

File: packages/next-typescript/index.js (hunk 1 above)
Comment (zscaiosi) [reply packages/next-typescript/index.js]: @timneutkens before I make the changes I would like to ask something.
I've tried to change it directly from node_modules/@zeit/next-typescript/index.js setting transpileOnly to "false".

But it still doesn't raise any errors, as long as I changed the lib "hard coding it" it should work right?

Can you give me a light please?

**Comment by zscaiosi** [comment]
@timneutkens before I make the changes I would like to ask something.
I've tried to change it directly from node_modules/@zeit/next-typescript/index.js setting transpileOnly to "false". (just for checking if it would work)

But it still doesn't raise any errors, as long as I changed the lib "hard coding it" it should work right?

Can you give me a hand please?

**Comment by timneutkens** [comment]
I'm not very familiar with ts-loader, which next-typescript just adds to webpack, as far as the docs say changing transpileOnly to false should work fine.
https://github.com/TypeStrong/ts-loader#transpileonly-boolean-defaultfalse

**Comment by zscaiosi** [comment]
Ok @timneutkens , I did the requested modifications, it should work now.

Is it ok for a rebase and merge now?

**Comment by timneutkens** [comment]
@zscaiosi very nice 🙏
